name: python_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy=2.2.6
  - pyqt6=6.10.1


  - pip:
      - -r requirements.txt
      - pillow==12.1.0
      - pyserial==3.5
